#!/bin/bash
# =============================================================================
# Build + install a double-clickable Recorder.app for macOS.
#
# WHY AN INSTALLER (not just a launcher pointing at this folder)?
#   macOS TCC blocks Finder-launched apps from reading ~/Documents, ~/Desktop,
#   ~/Downloads. This project lives under ~/Documents, so an app that runs code
#   from here crashes at startup with a PermissionError. The fix is to run the
#   app from a NON-protected location. We install a runnable copy + the venv to
#   ~/Library/Application Support/Recorder, and build the .app to launch from
#   there — no Full Disk Access prompts, true double-click.
#
#   The .app carries its own copy of the code (Contents/Resources/Recorder) and
#   its launcher resolves every path at run time: each launch syncs that copy
#   into Application Support when it changed and makes sure the venv there
#   matches requirements.txt. So this very bundle is also what the release
#   workflow zips — a downloaded Recorder.app installs itself on first launch.
#
#   Dev editing still happens in this folder; re-run this script to re-sync.
#
# WHY NOT py2app / PyInstaller? They try to freeze torch + mlx into the bundle
# (gigabytes, fragile). The launcher approach keeps `pip install -U` working.
#
# Usage:   ./make_app.sh
# Output:  /Applications/Recorder.app  (and ~/Library/Application Support/Recorder)
# =============================================================================
set -euo pipefail
cd "$(dirname "$0")"

SRC_DIR="$(pwd)"
APP_HOME="$HOME/Library/Application Support/Recorder"
APP="/Applications/Recorder.app"
CODE="$APP/Contents/Resources/Recorder"   # the copy the launcher installs from

echo "=== Recorder installer ==="
echo "source : $SRC_DIR"
echo "install: $APP_HOME"

# --- 1) Build the .app launcher ---------------------------------------------
echo "→ building $APP …"
rm -rf "$APP"
mkdir -p "$APP/Contents/MacOS" "$APP/Contents/Resources" "$CODE"

cat > "$APP/Contents/Info.plist" << PLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN"
  "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>CFBundleName</key>            <string>Recorder</string>
  <key>CFBundleDisplayName</key>     <string>Recorder</string>
  <key>CFBundleIdentifier</key>      <string>com.lucaslab.recorder</string>
  <key>CFBundleVersion</key>         <string>2.1.0</string>
  <key>CFBundleShortVersionString</key><string>2.1</string>
  <key>CFBundlePackageType</key>     <string>APPL</string>
  <key>CFBundleExecutable</key>      <string>Recorder</string>
  <key>NSMicrophoneUsageDescription</key>
  <string>Recorder 需要使用麦克风进行录音转写。</string>
  <key>NSHighResolutionCapable</key> <true/>
  <key>LSMinimumSystemVersion</key>  <string>12.0</string>
</dict>
</plist>
PLIST

# Quoted heredoc: nothing from this machine is baked in, so the bundle is portable.
cat > "$APP/Contents/MacOS/Recorder" << 'LAUNCHER'
#!/bin/bash
# Auto-generated by make_app.sh. Installs the code embedded in this bundle into
# the non-protected Application Support dir (and a venv for it) when needed,
# then runs Recorder from there. Every path is resolved at run time.
APP_HOME="$HOME/Library/Application Support/Recorder"
BUNDLED="$(cd "$(dirname "$0")/../Resources/Recorder" 2>/dev/null && pwd)"
VENV="$APP_HOME/.venv"
READY="$VENV/.recorder-requirements"   # hash of the requirements.txt last installed
LOG="$HOME/Library/Logs/Recorder.log"
# The bundled ffmpeg (bin/) first, then Homebrew's: Finder gives apps a bare PATH.
export PATH="$APP_HOME/bin:/opt/homebrew/bin:/usr/local/bin:$HOME/.local/bin:$PATH"

mkdir -p "$APP_HOME" "$(dirname "$LOG")"
# make_app.sh and CI set RECORDER_BOOTSTRAP_ONLY=1: install, print here, don't open the GUI.
[[ -n "${RECORDER_BOOTSTRAP_ONLY:-}" ]] || exec >> "$LOG" 2>&1

notify() {   # log line, plus a dialog when launched from Finder
  echo "[Recorder] $1"
  [[ -n "${RECORDER_BOOTSTRAP_ONLY:-}" ]] && return 0
  osascript -e 'on run argv' -e 'display alert "Recorder" message (item 1 of argv)' \
    -e 'end run' "$1" >/dev/null 2>&1
}

requirements_hash() { shasum -a 256 "$APP_HOME/requirements.txt" 2>/dev/null | cut -d' ' -f1; }
code_stale() { [[ -f "$BUNDLED/.build-id" ]] && ! cmp -s "$BUNDLED/.build-id" "$APP_HOME/.build-id"; }
venv_stale() { [[ ! -x "$VENV/bin/python3" || "$(cat "$READY" 2>/dev/null)" != "$(requirements_hash)" ]]; }

find_uv() {   # the bundled copy first (known version), then one on PATH
  local uv
  for uv in "$APP_HOME/bin/uv" "$(command -v uv)"; do
    if [[ -n "$uv" && -x "$uv" ]] && "$uv" --version >/dev/null 2>&1; then
      echo "$uv"; return 0
    fi
  done
  return 1
}

setup() {
  if code_stale; then
    echo "[Recorder] installing build $(cat "$BUNDLED/.build-id") into $APP_HOME"
    (cd "$BUNDLED" && rsync -a --delete ./* "$APP_HOME/") || return 1
    # A downloaded zip quarantines every file; clear it on the executables we run.
    xattr -dr com.apple.quarantine "$APP_HOME/bin" "$APP_HOME/native" 2>/dev/null
    cp "$BUNDLED/.build-id" "$APP_HOME/.build-id" || return 1
  fi
  venv_stale || return 0

  notify "正在安装运行环境（需联网下载依赖，可能要几分钟），完成后 Recorder 会自动打开。" &
  local uv
  links=()   # prebuilt wheels for sdist-only deps, bundled by make_app.sh
  [[ -d "$APP_HOME/wheels" ]] && links=(--find-links "$APP_HOME/wheels")
  if uv="$(find_uv)"; then
    [[ -x "$VENV/bin/python3" ]] || { rm -rf "$VENV"; "$uv" venv --python 3.11 "$VENV"; } || return 1
    "$uv" pip install --python "$VENV/bin/python3" "${links[@]}" -r "$APP_HOME/requirements.txt" || return 1
  else
    [[ -x "$VENV/bin/python3" ]] || { rm -rf "$VENV"; python3 -m venv "$VENV"; } || return 1
    "$VENV/bin/python3" -m pip install "${links[@]}" -r "$APP_HOME/requirements.txt" || return 1
  fi
  requirements_hash > "$READY"
}

prune_webengine() {
  [[ -x "$VENV/bin/python3" && -f "$APP_HOME/prune_qt_webengine.py" ]] || return 0
  "$VENV/bin/python3" "$APP_HOME/prune_qt_webengine.py" || \
    echo "[Recorder] warning: could not remove unused Qt WebEngine files"
}

if code_stale || venv_stale; then
  LOCK="$APP_HOME/.setup.lock"   # a second double-click must not install concurrently
  if ! mkdir "$LOCK" 2>/dev/null; then
    if kill -0 "$(cat "$LOCK/pid" 2>/dev/null)" 2>/dev/null; then
      notify "Recorder 正在安装运行环境，完成后会自动打开。"
      exit 0
    fi
    rm -rf "$LOCK"; mkdir "$LOCK" || exit 0   # stale lock from an interrupted setup
  fi
  echo $$ > "$LOCK/pid"
  setup; status=$?
  rm -rf "$LOCK"
  if (( status != 0 )); then
    notify "安装运行环境失败，请检查网络后重新打开 Recorder。详情见 ~/Library/Logs/Recorder.log"
    exit 1
  fi
fi

prune_webengine

[[ -n "${RECORDER_BOOTSTRAP_ONLY:-}" ]] && exit 0
cd "$APP_HOME"
exec "$VENV/bin/python3" "$APP_HOME/app.py"
LAUNCHER
chmod +x "$APP/Contents/MacOS/Recorder"

[[ -f "Resources/icon.icns" ]] && cp "Resources/icon.icns" "$APP/Contents/Resources/icon.icns"

# --- 2) Embed the code (small) ----------------------------------------------
echo "→ embedding code…"
for item in core gui modules app.py transcribe.py download_models.py prune_qt_webengine.py requirements.txt README.md; do
  if [[ -e "$item" ]]; then
    rsync -a --exclude '.venv' --exclude 'dist' --exclude '__pycache__' \
      --exclude '*.pyc' --exclude 'models' --exclude 'output' "$item" "$CODE/"
  fi
done

# --- 2b) Compile the native system-audio (ScreenCaptureKit) helper ----------
mkdir -p "$CODE/native"
if command -v swiftc >/dev/null 2>&1; then
  echo "→ compiling system-audio helper…"
  if swiftc -O -target "$(uname -m)-apple-macos13.0" "$SRC_DIR/native/SystemAudioRecorder.swift" \
       -o "$CODE/native/system_audio_recorder"; then
    echo "  ✓ system_audio_recorder built"
  else
    echo "  ! swiftc failed — '电脑声音' capture will be unavailable"
  fi
elif [[ -x "$SRC_DIR/native/system_audio_recorder" ]]; then
  cp "$SRC_DIR/native/system_audio_recorder" "$CODE/native/"
else
  echo "  ! no swiftc and no prebuilt helper — '电脑声音' capture unavailable"
fi
rmdir "$CODE/native" 2>/dev/null || true   # nothing built: leave an installed helper alone

# --- 2c) Bundle uv, so a Mac without Python can still build the venv --------
UV_BIN="$(command -v uv || true)"
if [[ -n "$UV_BIN" ]]; then
  mkdir -p "$CODE/bin"
  cp -L "$UV_BIN" "$CODE/bin/uv"
  echo "  ✓ bundled $("$CODE/bin/uv" --version)"

  # webrtcvad (required by resemblyzer) ships only as an sdist; prebuild its
  # wheel so first launch works on a Mac without Xcode Command Line Tools.
  echo "→ prebuilding webrtcvad wheel…"
  if MACOSX_DEPLOYMENT_TARGET=11.0 "$UV_BIN" tool run --python 3.11 pip wheel -q \
       --no-deps -w "$CODE/wheels" webrtcvad; then
    echo "  ✓ $(ls "$CODE/wheels")"
  else
    echo "  ! wheel build failed — first launch will compile webrtcvad itself"
  fi
else
  echo "  ! uv not found — first launch will fall back to python3 -m venv"
fi

# --- 2d) Bundle ffmpeg + ffprobe when build_ffmpeg.sh has produced them ----
# The release workflow always does; a dev build without them uses Homebrew's.
if [[ -x dist/ffmpeg/bin/ffmpeg && -x dist/ffmpeg/bin/ffprobe ]]; then
  mkdir -p "$CODE/bin"
  cp dist/ffmpeg/bin/* "$CODE/bin/"
  echo "  ✓ bundled $("$CODE/bin/ffmpeg" -hide_banner -version | head -1)"
else
  echo "  ! no dist/ffmpeg (run ./build_ffmpeg.sh) — the app will need ffmpeg on PATH"
fi

# Stamp the build: the launcher re-syncs the code whenever this changes.
echo "$(git -C "$SRC_DIR" describe --tags --always --dirty 2>/dev/null || echo unknown)" \
  "$(date -u +%Y%m%dT%H%M%SZ)" > "$CODE/.build-id"

# --- 3) Move a dev venv out of the protected folder --------------------------
mkdir -p "$APP_HOME"
if [[ -x "$APP_HOME/.venv/bin/python3" ]]; then
  echo "→ reusing existing install venv"
elif [[ -x "$SRC_DIR/.venv/bin/python3" && ! -L "$SRC_DIR/.venv" ]]; then
  # Instant same-volume rename, leaving a symlink behind so terminal/dev use
  # keeps working.
  echo "→ relocating venv to install location (instant rename)…"
  mv "$SRC_DIR/.venv" "$APP_HOME/.venv"
  ln -s "$APP_HOME/.venv" "$SRC_DIR/.venv"
else
  echo "→ creating fresh venv (downloads dependencies, one time)…"
fi

# --- 4) Install code + dependencies exactly as a first launch would ---------
RECORDER_BOOTSTRAP_ONLY=1 "$APP/Contents/MacOS/Recorder"

echo ""
echo "✓ Installed: $APP"
echo "  Code + venv: $APP_HOME"
echo ""
echo "Double-click Recorder in /Applications (or Launchpad)."
echo "First launch: right-click → Open to clear Gatekeeper, then allow the mic."
echo "Logs: ~/Library/Logs/Recorder.log"
